### ISSUE TITLE
sampling edge collection

### ISSUE THREAD

**Issue by echo66** [meteor-shuttler/graphs#6]
Greetings, Ivan!

To allow easy sampling of an edge collection, you could have something like this:

``` javascript
Docs = new Mongo.Collection('docs');
Edges = new Mongo.Collection('edges');
Edges.attachGraph();
Edges.links.find(null, null, {}, {sampling: true, sampleSize: 10});
```

This code would give you, at most, 10 random edges.

**Comment by echo66** [comment]
Or, for example, 5 random edges with a certain document as source:

``` javascript
Edges.link.find.from(Docs.findOne(), {}, {sampling: true, sampleSize: 5});
```

**Comment by ivansglazunov** [comment]
#### Graph methods

Methods in the graph is sugar. They have an alternative, and probably it is necessary to write the documentation.

``` js
Edges.link.find.from(Docs.findOne());
Edges.find(Docs.findOne().Ref('_source'));
```

#### Sampling

This applies not so much graphs how much random in mongodb.
I propose to make a package that can so:

``` js
// Because in mongo is not have random selector as far as i know, we can fix it at the cursor step.
var cursor = Edges.find();
cursor.cout();
// 150
cursor.random(3);
// [Document, Document, Document]
Edges.links.find.from(Docs.findOne()).random(5);
// [Document, Document, Document, Document, Document]
```

**Comment by ivansglazunov** [comment]
Implement sampling can be something like this:

``` js
var cursor = Edges.find();
var results = [];
var hash = {};
var collection = Mongo.Collection.get(cursor.collection.name);
for (var s = 0; s <= 5; s++) {
    while (true) {
        var random = lodash.random(0, cursor.count()-1);
        if (!hash[random]) {
            hash[random] = true;
            break;
        }
    }
    var document = collection.findOne(cursor.matcher._selector, { skip: random, limit: 1 });
    results.push(document);
}
```

I can arrange it in the package if needed.

**Comment by echo66** [comment]
Why don't you use the 'options' argument to state that you want a sample of the edge collection? That would allow the API to stay the same.

**Comment by ivansglazunov** [comment]
API is different. We can say that the options of the method find, to get the API cursor is unchanged, but the cursor function and collection functions can be changed, or vice versa. Following the tradition of [hooks](https://github.com/matb33/meteor-collection-hooks) or [helpers](https://github.com/dburles/meteor-collection-helpers/) or [instances](https://github.com/dburles/mongo-collection-instances) and others, it seems logical to add a method. However, nothing prevents to do both?
Options for the database will have to be validated on each request and remove our excesses from official options in minimongo. This will cause an additional burden on each operation. The loads will not be if it is just a method to the prototype cursor.
